errors:
  Allcaps: 10
  Fragment: 10
  Capitalization: 9
  Repeated conjunction: 9
  Repeated word: 8
  Possessive pronouns: 7
  Subject pronouns: 6
  Object pronouns: 6
  Incorrect past tense as participle in passive: 0
  Passive with simple past instead of participle: 0
  Passive perfect with incorrect participle: 0
  Passive perfect without have: 0
  Passive with incorrect be: 0
  Passive without be: 0
  Perfect without have: 0
  Past tense instead of participle: 0
  Perfect progressive with incorrect be and without have: 5
  Perfect progressive without have: 0
  Perfect with incorrect participle: 0
  Commas after yes & no: 0
  Commas in numbers: 0
  Irregular plural nouns: 0
  Contractions: 5
  Spacing: 4
  Incorrect irregular past tense: 0
  Subject verb agreement with collective noun: 0
  Subject verb agreement with indefinite pronoun: 0
  Subject verb agreement with simple noun: 2
  Subject verb agreement with personal pronoun: 1
  Subject verb agreement with inversion: 0
  Subject verb agreement with either or: 0
  Subject verb agreement with neither nor: 0
  Subject verb agreement with separate subject and verb: 0
  Punctuation: 1
  Question marks: 0
  Plural versus possessive nouns: 0
  This versus that: 0
  Articles: 0
  Woman versus women: 0
  Man versus men: 0
  Child versus children: 0
  Its versus it's: 0
  Than versus then: 0
  Singular and plural nouns: 0
  Incorrect participle: 0
  Simple past instead of past perfect: 0
