errors:
  - Spacing
  - Articles
  - Subject pronouns
  - Object pronouns
  - Commas in numbers
  - Commas after yes & no
  - Capitalization
  - Contractions
  - Punctuation
  - Irregular plural nouns
  - Subject_verb agreement with inversion
  - Subject_verb agreement with either_or
  - Subject_verb agreement with collective noun
  - Subject_verb agreement with neither_nor
  - Subject_verb agreement with simple noun
  - Subject_verb agreement with personal pronoun
  - Subject_verb agreement with separate subject and verb
  - Subject_verb agreement with indefinite pronoun
