errors:
  Plural versus possessive nouns: 1
  This versus that: 1
  Question marks: 0
  Spacing: 1
  Articles: 1
  Woman versus women: 1
  Man versus men: 1
  Incorrect irregular past tense: 1
  Than versus then: 1
  Repeated word: 1
  Subject pronouns: 1
  Object pronouns: 1
  Commas in numbers: 1
  Commas after yes & no: 1
  Singular and plural nouns: 1
  Capitalization: 1
  Contractions: 1
  Incorrect participle: 1
  Punctuation: 1
  Irregular plural nouns: 1
  Fragment: 1
  Possessive pronouns: 1
  Perfect progressive without have: 1
  Passive without be: 1
  Perfect without have: 1
  Perfect progressive with incorrect be and without have: 1
  Its versus it's: 1
  Subject_verb agreement with inversion: 1
  Subject_verb agreement with either_or: 1
  Subject_verb agreement with collective noun: 1
  Subject_verb agreement with neither_nor: 1
  Subject_verb agreement with simple noun: 1
  Subject_verb agreement with personal pronoun: 1
  Subject_verb agreement with separate subject and verb: 1
  Subject_verb agreement with indefinite pronoun: 1
  Child versus children: 1
  Passive with incorrect be: 1
  Simple past instead of past perfect: 1
  Passive perfect without have: 1