errors:
  Allcaps: 10
  Fragment: 10
  Response starts with verb: 10
  Capitalization: 9
  Repeated conjunction: 9
  Repeated word: 8
  Possessive pronouns: 7
  Subject pronouns: 6
  Object pronouns: 6
  Incorrect past tense as participle in passive: 5
  Passive with simple past instead of participle: 5
  Passive perfect with incorrect participle: 5
  Passive perfect without have: 5
  Passive with incorrect be: 5
  Passive without be: 11  # Needs to have a score higher than Fragment to avoid confusion
  Perfect without have: 5
  Past instead of participle: 5
  Perfect progressive with incorrect be and without have: 5
  Perfect progressive without have: 5
  Perfect with incorrect participle: 5
  Commas after yes & no: 5
  Commas in numbers: 5
  Irregular plural nouns: 5
  Contractions: 5
  Spacing: 4
  Incorrect irregular past tense: 4
  Subject verb agreement with collective noun: 4
  Subject verb agreement with indefinite pronoun: 4
  Subject verb agreement with simple noun: 3
  Subject verb agreement with personal pronoun: 3
  Subject verb agreement with inversion: 3
  Subject verb agreement with either or: 0
  Subject verb agreement with neither nor: 0
  Subject verb agreement with separate subject and verb: 0
  Punctuation: 9
  Question marks: 0
  Plural versus possessive nouns: 6  # needs to be higher than Singular and plural nouns
  This versus that: 1
  Articles: 1
  Woman versus women: 1
  Man versus men: 1
  Child versus children: 1
  Its versus it's: 1
  Than versus then: 1
  Singular and plural nouns: 5  # Needs to be higher than Articles, because "an unicycles" should trigger this. Should also be higher than SVA
  Incorrect participle: 1
  Simple past instead of past perfect: 0